export global CatppuccinMocha {
    // Monochromatic (Backgrounds, Overlays, and Text)
    out property <color> rosewater: #f5e0dc;
    out property <color> flamingo:  #f2cdcd;
    out property <color> pink:      #f5c2e7;
    out property <color> mauve:     #cba6f7;
    out property <color> red:       #f38ba8;
    out property <color> maroon:    #eba0ac;
    out property <color> peach:     #fab387;
    out property <color> yellow:    #f9e2af;
    out property <color> green:     #a6e3a1;
    out property <color> teal:      #94e2d5;
    out property <color> sky:       #89dceb;
    out property <color> sapphire:  #74c7ec;
    out property <color> blue:      #89b4fa;
    out property <color> lavender:  #b4befe;

    // Surface & Text hierarchy
    out property <color> text:      #cdd6f4;
    out property <color> subtext1:  #bac2de;
    out property <color> subtext0:  #a6adc8;
    out property <color> overlay2:  #9399b2;
    out property <color> overlay1:  #7f849c;
    out property <color> overlay0:  #6c7086;
    out property <color> surface2:  #585b70;
    out property <color> surface1:  #45475a;
    out property <color> surface0:  #313244e0;
    out property <color> base:      #1e1e2eca;
    out property <color> mantle:    #181825;
    out property <color> crust:     #11111b;
}